CREATE TABLE IF NOT EXISTS client_category (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT ClientCategory_unique_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS water_tariff_table (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    client_category_id INTEGER NOT NULL REFERENCES client_category(id),
    start_time_utc TIMESTAMP NOT NULL,
    end_time_utc TIMESTAMP,
    PRIMARY KEY(id)
);

CREATE INDEX IF NOT EXISTS WaterTariffTable_endTimeUtc_clientCategory_idx
    ON water_tariff_table (end_time_utc, client_category_id);

CREATE TABLE IF NOT EXISTS water_tariff_table_range (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    water_tariff_table_id BIGINT NOT NULL REFERENCES water_tariff_table(id),
    range_start_in_m3 INTEGER NOT NULL,
    range_end_in_m3 INTEGER,
    price_per_m3_in_cents BIGINT NOT NULL,
    PRIMARY KEY(id)
);

CREATE INDEX IF NOT EXISTS WaterTariffTableRange_tariffTableId_rangeStart_rangeEnd_idx
    ON water_tariff_table_range (water_tariff_table_id, range_start_in_m3, range_end_in_m3);